import pandas as pd

default_values = [[0] * 37]

feature_headers = pd.DataFrame(default_values ,columns=["OPERA_Aerolineas Argentinas",
"OPERA_Aeromexico",
"OPERA_Air Canada",
"OPERA_Air France",
"OPERA_Alitalia",
"OPERA_American Airlines",
"OPERA_Austral",
"OPERA_Avianca",
"OPERA_British Airways",
"OPERA_Copa Air",
"OPERA_Delta Air",
"OPERA_Gol Trans",
"OPERA_Grupo LATAM",
"OPERA_Iberia",
"OPERA_JetSmart SPA",
"OPERA_K.L.M.",
"OPERA_Lacsa",
"OPERA_Latin American Wings",
"OPERA_Oceanair Linhas Aereas",
"OPERA_Plus Ultra Lineas Aereas",
"OPERA_Qantas Airways",
"OPERA_Sky Airline",
"OPERA_United Airlines",
"TIPOVUELO_I",
"TIPOVUELO_N",
"MES_1",
"MES_2",
"MES_3",
"MES_4",
"MES_5",
"MES_6",
"MES_7",
"MES_8",
"MES_9",
"MES_10",
"MES_11",
"MES_12"])